language: python
cache: pip
python:
  - "3.5"

before_install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python data_utils/gen_captcha.py -dl --npi 2 -n 5

script:  "python cnn_n_char.py --data_dir images/char-2-epoch-5/"